In [1]:
import numpy as np
np_array = np.array([0, 1, 2, 3])


In [2]:
np_zero_array=  np.zeros(10)

In [3]:
np_zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 1. Ví dụ về phép cộng, từ hai ma trận numpy

In [12]:
# Cộng 2 ma trận 2 X 3
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b =  np.array([[7, 8, 9],
               [10, 11, 12]])
a + b, np.add(a, b)
a - b, np.subtract(a, b)

(array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]))

In [14]:
def predict(data, w):
    return data.dot(w)

w = np.array([0.1, 0.2, 0.3])

data1 = np.array([0.3, 1.5, 2.8])
data2 = np.array([0.5, 0.4, 0.9])
data3 = np.array([2.3, 3.1, 0.5])
data_in = np.array([data1[0], data2[0], data3[0]])

print('Predict value: $%.2f' % predict(data_in, w))

Predict value: $0.82


In [16]:
from sklearn.linear_model import LinearRegression

X = np.array([[3], [5], [7], [9], [11]]).reshape(-1, 1)
y = [8.0, 9.1, 10.3, 11.4, 12.6]
lreg_model = LineaerRegression()
lreg_model.fit(X, y)

new_data = np.array([[13]])
print('Model Prediction for new data: $%.2f' & lreg_model(new_data)[0])

NameError: name 'LineaerRegression' is not defined